// <auto-generated />
using System;
using InvoiceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceApp.Migrations.Invoice
{
    [DbContext(typeof(InvoiceContext))]
    partial class InvoiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("InvoiceApp.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Riyadh",
                            ClientName = "Alaa",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Alaa@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 26),
                            Number = "100052",
                            Phone = "0583997234",
                            Quantity = 30,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Khobar",
                            ClientName = "Nora",
                            Email = "Nora@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 15),
                            Number = "100053",
                            Phone = "0526679976",
                            Quantity = 50,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Khobar",
                            ClientName = "Anwar",
                            Email = "Anwar@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 22),
                            Number = "100054",
                            Phone = "0589654997",
                            Quantity = 6,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Qassim",
                            ClientName = "Hala",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Hala@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 11),
                            Number = "100055",
                            Phone = "0588283374",
                            Quantity = 12,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 5,
                            Address = "Jeddah",
                            ClientName = "Samar",
                            Email = "Samar@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 3),
                            Number = "100056",
                            Phone = "0527763834",
                            Quantity = 16,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 6,
                            Address = "Riyadh",
                            ClientName = "Sara",
                            DueDate = new DateOnly(2024, 1, 30),
                            Email = "Sara@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 22),
                            Number = "100057",
                            Phone = "0582336556",
                            Quantity = 14,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 7,
                            Address = "Medina",
                            ClientName = "Shahad",
                            Email = "Shahad@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 10),
                            Number = "100058",
                            Phone = "0577743112",
                            Quantity = 15,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 8,
                            Address = "Abha",
                            ClientName = "Rasha",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Rasha@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 17),
                            Number = "100059",
                            Phone = "0584455161",
                            Quantity = 22,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 9,
                            Address = "Qassim",
                            ClientName = "Aseel",
                            Email = "Aseel@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 25),
                            Number = "100060",
                            Phone = "0567768899",
                            Quantity = 21,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 10,
                            Address = "Riyadh",
                            ClientName = "Razan",
                            Email = "Razan@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 25),
                            Number = "100061",
                            Phone = "0565567543",
                            Quantity = 13,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 11,
                            Address = "Makkah",
                            ClientName = "Fai",
                            Email = "Fai@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 13),
                            Number = "100062",
                            Phone = "0550537233",
                            Quantity = 42,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 12,
                            Address = "Jeddah",
                            ClientName = "Nouf",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Nouf@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 10),
                            Number = "100063",
                            Phone = "058557616",
                            Quantity = 25,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 13,
                            Address = "Riyadh",
                            ClientName = "Mada",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Mada@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 10),
                            Number = "100064",
                            Phone = "0582627534",
                            Quantity = 32,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 14,
                            Address = "Medina",
                            ClientName = "Abrar",
                            Email = "Abrar@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 18),
                            Number = "100065",
                            Phone = "0500716634",
                            Quantity = 36,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 15,
                            Address = "Makkah",
                            ClientName = "Bayan",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Bayan@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 7),
                            Number = "100066",
                            Phone = "0565566763",
                            Quantity = 27,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 16,
                            Address = "Qassim",
                            ClientName = "Raseel",
                            Email = "Raseel@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 3),
                            Number = "100067",
                            Phone = "0562923776",
                            Quantity = 19,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 17,
                            Address = "Jeddah",
                            ClientName = "Sama",
                            Email = "Sama@gmail.com",
                            IssueDate = new DateOnly(2025, 1, 7),
                            Number = "100068",
                            Phone = "0532726164",
                            Quantity = 17,
                            Service = "Proofreading",
                            Status = "Pending",
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 18,
                            Address = "Khobar",
                            ClientName = "Rama",
                            DueDate = new DateOnly(2024, 12, 30),
                            Email = "Rama@gmail.com",
                            IssueDate = new DateOnly(2024, 12, 9),
                            Number = "100069",
                            Phone = "0526673176",
                            Quantity = 24,
                            Service = "Proofreading",
                            Status = "Paid",
                            UnitPrice = 12.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
